// <auto-generated />
using System;
using BlogManager_LeTrongKha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogManager_LeTrongKha.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803014014_SeedPosts")]
    partial class SeedPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("BlogManager_LeTrongKha.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BlogManager_LeTrongKha.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Lê Trọng Kha",
                            Content = "Các kiến thức C# cần thiết để học ASP.NET Core.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# cơ bản",
                            ViewCount = 120
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lê Trọng Kha",
                            Content = "Tìm hiểu vai trò của Model, View và Controller.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MVC nhập môn",
                            ViewCount = 85
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lê Trọng Kha",
                            Content = "Làm việc với cơ sở dữ liệu bằng Entity Framework Core.",
                            IsPublished = false,
                            PublishedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EF Core",
                            ViewCount = 240
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
